Update Sell and ItemEnhancement
planetarium/lib9c pull request #1045
Opened 2022-05-25 02:33 UTC by hskim881028

- Update `Sell` and `ItemEnhancement`
   - Added a function to unequip arena avatar item
   - item_enhancement10 -> item_enhancement11
   - sell10 ->sell11
- When releasing the mainnet, we should add `Obsolete Block Index` into `Sell10` and `ItemEnhancement10`

2022-05-25 04:10 UTC, area363 approved these changes

2022-05-27 01:29 UTC, ipdae requested changes
ItemEnhancement was hard forked once in the 2022q2 branch, so we can just change code without additional hard forking.

2022-05-27 01:32 UTC, boscohyun approved these changes

2022-05-27 04:44 UTC, hskim881028 commented
> 

Fixed it. Please check again. 🙏🏻 @ipdae

2022-06-30 06:07 UTC, closed without merging