feat: buy ticket if needed on `EventDungeonBattle`
planetarium/lib9c pull request #1285
Opened 2022-08-10 09:35 UTC by boscohyun

- Add some fields to `EventScheduleSheet`
  - `int DungeonTicketPrice`
  - `int DungeonTicketAdditionalPrice`
  - It's same logic with `Arena`.
- Add `NumberOfTicketPurchases` property to `EventDungeonInfo`
- Add `EventDungeon` address to `Addresses`
- Add `GetDungeonTicketCost()` extension method for `EventScheduleSheet.Row`
- Add `BuyTicketIfNeeded` field to `EventDungeonBattle` action

2022-08-10 10:02 UTC, hskim881028 requested changes

2022-08-10 10:02 UTC, hskim881028 commented on Lib9c/Addresses.cs
> +        public static readonly Address EventDungeon          = new Address("0000000000000000000000000000000000000013");
You are using duplicate values
https://github.com/planetarium/lib9c/pull/1264/files#diff-96afdc7d05f26c279c28aacc5f8640dd91e7f96ff81b192e626ee1ee85ab8575R31

2022-08-12 01:52 UTC, Unengine approved these changes

2022-08-12 01:54 UTC, sonohoshi approved these changes

2022-08-12 02:27 UTC, merged