Hard fork `ClaimStakeReward` from 1 to 2
planetarium/lib9c pull request #1371
Opened 2022-09-13 08:46 UTC by boscohyun

This pull request based on #1370 

Resolve https://github.com/planetarium/NineChronicles/issues/1933

2022-09-13 09:01 UTC, moreal requested changes
If there is a chance to restart the chain, we must consider hard a strategy for actions and models versioning

2022-09-13 09:25 UTC, boscohyun commented on .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
> -        }
@moreal You can check this test at line number 100. That's not removed.😅

2022-09-13 09:27 UTC, moreal commented on .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
> -        }
It's too hard to look the changes 😞 I see, thanks!

2022-09-13 09:27 UTC, boscohyun commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
@moreal Fixed! thanks!

2022-09-13 09:30 UTC, moreal commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
@boscohyun If you have no antipathy for force-push, could you amend the `Fix typo` commit into `Hard fork ClaimStakeReward from 1 to 2`. I'm worrying the case when someone cherry-pick the `Hard fork ClaimStakeReward from 1 to 2` commit only.

2022-09-13 09:33 UTC, boscohyun commented on .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
> -        }
Sorry for moving some features. For encapsulation, I had to change the access modifiers of some functions to private. The code analyzer then drew a red line, guiding me to change the order of the functions to public-first.😇

2022-09-13 09:35 UTC, boscohyun commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
@moreal Oh, I cannot think about that case. Thanks for your review.

2022-09-13 09:35 UTC, moreal commented on .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
> -        }
You're right, I don't want to blame you. It's just my mistake! 👍🏻

2022-09-13 09:36 UTC, boscohyun commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
@moreal Applied!

2022-09-13 09:37 UTC, moreal commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
After the based pull request was merged, this pull request may be able to merge.

2022-09-13 09:39 UTC, boscohyun commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
That's exactly what I want.

2022-09-14 01:19 UTC, ipdae approved these changes

2022-09-14 04:30 UTC, boscohyun commented on Lib9c/Action/ClaimStakeReward.cs
> +    [ActionType("ActionTypeText")]
@moreal The based pull request was merged!

2022-09-14 05:41 UTC, moreal approved these changes

2022-09-14 05:41 UTC, moreal commented on Lib9c/Action/AccountStateDeltaExtensions.cs
> +            out StakeState stakeState)
It's minor but I hope the part formatting code separated as other pull request or commit.

2022-09-14 05:41 UTC, merged