Apply Libplanet.Analyzer.CSharp
planetarium/lib9c pull request #138
Opened 2020-10-13 10:54 UTC by dahlia

*(This should be merged after <https://github.com/planetarium/libplanet/pull/1028> is merged.)*

This applies *Libplanet.Analyzer.CSharp* to *Lib9c*.  With this analyzer, if we make a change like below:

```diff
diff --git a/Lib9c/Action/CreateAvatar.cs b/Lib9c/Action/CreateAvatar.cs
index 8931d6e..63dc575 100644
--- a/Lib9c/Action/CreateAvatar.cs
+++ b/Lib9c/Action/CreateAvatar.cs
@@ -81,10 +81,11 @@ namespace Nekoyume.Action
                     $"Aborted as the input name {name} does not follow the allowed name pattern.");
             }
 
+            var r = new Random();
             var sw = new Stopwatch();
             sw.Start();
             var started = DateTimeOffset.UtcNow;
-            Log.Debug("CreateAvatar exec started.");
+            Log.Debug($"CreateAvatar exec started. {r.Next()}");
             AgentState existingAgentState = states.GetAgentState(ctx.Signer);
             var agentState = existingAgentState ?? new AgentState(ctx.Signer);
             var avatarState = states.GetAvatarState(avatarAddress);
```

The compiler warns like the following:

```
Action/CreateAvatar.cs(84,21): error LAC1001: The System.Random makes an IAction.Execute() method indeterministic; use IActionContext.Random property instead.
```

2020-10-15 01:44 UTC, ipdae approved these changes

2020-10-15 02:07 UTC, earlbread approved these changes

2020-10-15 02:55 UTC, limebell commented
Build seems fail 😥

2020-10-16 01:06 UTC, longfin approved these changes

2020-10-16 01:07 UTC, longfin requested changes
Build seems to fail [again](https://github.com/planetarium/lib9c/pull/138/checks?check_run_id=1259059049#step:5:26).

2020-10-16 13:07 UTC, moreal approved these changes

2020-10-19 02:22 UTC, limebell approved these changes

2020-10-19 09:13 UTC, dahlia commented
@boscohyun @ipdae @Unengine Could you check if the commit 4e70bdfea5018b44656f9c81bbff545126a12eaf makes `dotnet build` to fail (it should fail) with LAA1002 errors on your local environment?

2020-10-19 09:20 UTC, ipdae commented
@dahlia 
```PS C:\Users\qoora\projects\lib9c> dotnet build
.NET Core용 Microsoft (R) Build Engine 버전 16.5.0+d4cbfca49
Copyright (C) Microsoft Corporation. All rights reserved.

  90.09 ms에서 C:\Users\qoora\projects\lib9c\Lib9c\Lib9c.csproj에 대한 복원을 완료했습니다.
  90.09 ms에서 C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Stun\Libplanet.Stun.csproj에 대한 복원을 완료했습니다.
  90.1 ms에서 C:\Users\qoora\projects\lib9c\.Lib9c.Tools\Lib9c.Tools.csproj에 대한 복원을 완료했습니다.
  95.45 ms에서 C:\Users\qoora\projects\lib9c\.Lib9c.Tools.Tests\Lib9c.Tools.Tests.csproj에 대한 복원을 완료했습니다.
  95.81 ms에서 C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet\Libplanet.csproj에 대한 복원을 완료했습니다.
  96.38 ms에서 C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Analyzers\Libplanet.Analyzers.csproj에 대한 복원을 완 료했습니다.
  97.31 ms에서 C:\Users\qoora\projects\lib9c\.Lib9c.Tests\Lib9c.Tests.csproj에 대한 복원을 완료했습니다.
  Libplanet.Stun -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Stun\bin\Debug\netstandard2.0\Libplanet.Stun.dll
  Libplanet -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet\bin\Debug\netstandard2.0\Libplanet.dll
  Libplanet.Stun -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Stun\bin\Debug\netstandard2.1\Libplanet.Stun.dll
  Libplanet.Analyzers -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Analyzers\bin\Debug\netstandard2.0\Libplanet.Analyzers.dll
  Libplanet.Stun -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Stun\bin\Debug\netcoreapp3.1\Libplanet.Stun.dll
  Libplanet -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet\bin\Debug\netstandard2.1\Libplanet.dll
  Libplanet -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet\bin\Debug\netcoreapp3.1\Libplanet.dll
  Libplanet.Analyzers -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Analyzers\bin\Debug\netstandard2.1\Libplanet.Analyzers.dll
  Libplanet.Analyzers -> C:\Users\qoora\projects\lib9c\.Libplanet\Libplanet.Analyzers\bin\Debug\netcoreapp3.1\Libplanet.Analyzers.dll
  Lib9c -> C:\Users\qoora\projects\lib9c\Lib9c\.bin\netstandard2.0\Lib9c.dll
  Lib9c.Tools -> C:\Users\qoora\projects\lib9c\.Lib9c.Tools\bin\Debug\netcoreapp3.1\9c-tools.dll
  Lib9c.Tools.Tests -> C:\Users\qoora\projects\lib9c\.Lib9c.Tools.Tests\bin\Debug\netcoreapp3.1\Lib9c.Tools.Tests.dll
  Lib9c.Tests -> C:\Users\qoora\projects\lib9c\.Lib9c.Tests\bin\Debug\netcoreapp3.1\Lib9c.Tests.dll

빌드했습니다.
    경고 0개
    오류 0개

경과 시간: 00:00:31.40```

2020-10-20 02:30 UTC, boscohyun approved these changes

2020-10-20 02:38 UTC, dahlia commented
I temporarily turned off LAA1002 in this pull request to merge it.  This should be turned on again.

2020-10-20 02:42 UTC, merged