Add limit about ticket buying in arena
planetarium/lib9c pull request #1455
Opened 2022-10-28 02:01 UTC by sonohoshi

- Add column in `ArenaSheet`
  - `MaxPurchaseCount`, `MaxPurchaseCountWithInterval`
- Version up action `BattleArena` to "battle_arena6"
  - Archive "battle_arena5"
- Add field in `ArenaInformation`
  - `PurchasedTicketCountDuringResetInterval`: int
  - Archive and version up `ResetTicket()`, `BuyTicket()`
- Obsolete `ArenaHelper.GetMaxPurchasedTicketCount()`

2022-10-28 04:38 UTC, hskim881028 commented on Lib9c/Model/Arena/ArenaInformation.cs
> +        public int PurchasedTicketCountDuringResetInterval { get; private set; }
I think the variable name is too long.

2022-10-28 04:49 UTC, ipdae requested changes
update ArenaInformation class version like hard-fork action

2022-10-28 04:49 UTC, ipdae commented on .Lib9c.Tests/Action/ArenahelperTest.cs
> +                    var max = roundData.MaxPurchaseCount;
divide test case instead of delete `GetMaxPurchasedTicketCount`

2022-10-28 04:49 UTC, ipdae commented on Lib9c/Model/Arena/ArenaInformation.cs
> +                .Add(PurchasedTicketCountDuringResetInterval);
it can be occur `InvalidBlockStateRootHashException`

2022-10-31 03:04 UTC, ipdae reviewed
is this ok without validate arena season for divide hard-forked model?

2022-10-31 03:04 UTC, ipdae commented on Lib9c/Arena/ArenaHelper.cs
> -                       (addTicketPrice.DivRem(100, out _) * arenaInformation.PurchasedTicketCount);
i can't find different case in this pr. is this correct change?

2022-10-31 03:04 UTC, ipdae commented on Lib9c/Model/Arena/ArenaInformation.cs
> +            }
serialized dictionary always contains interval field
```suggestion
            PurchasedTicketCountDuringInterval = (Integer) serialized[6];
```

2022-11-01 01:57 UTC, closed without merging