Bump Libplanet to 0.45.0
planetarium/lib9c pull request #1559
Opened 2022-12-02 18:56 UTC by longfin

It consists of these cherry-picks

- 623fa547cfcd5475c66af0049c8a89c6bf22c531
- e36166ba088db48993943b6c8bd6f487d6c13410

2022-12-05 06:28 UTC, greymistcube requested changes

2022-12-05 06:28 UTC, greymistcube commented on Lib9c/Policy/MinBlockProtocolVersionPolicy.cs
> +                    value: 4));
We need to set this to `Default`, otherwise the chain would stop. 😱

2022-12-07 10:33 UTC, dahlia approved these changes

2022-12-08 05:08 UTC, greymistcube commented on Lib9c/Policy/MinBlockProtocolVersionPolicy.cs
> +                    value: 4));
Added 500dc116b1041704551e6ff830b3faabc7ea6590.

2022-12-08 05:08 UTC, greymistcube approved these changes

2022-12-08 05:15 UTC, dahlia approved these changes

2022-12-09 02:03 UTC, merged