Introduce hack_and_slash20
planetarium/lib9c pull request #1628
Opened 2023-01-05 09:21 UTC by sonohoshi

- Add field: `ApStoneCount:int`
- Add throwing Exception `InvalidRepeatPlayException`, `NotEnoughMaterialException`, `UsageLimitExceedException`
- Remove throwing Exception `PlayCountIsZeroException`

2023-01-05 09:49 UTC, sonohoshi commented
```
[xUnit.net 00:08:36.24]     Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip [FAIL]
  Failed Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip [335 ms]
  Error Message:
   Nekoyume.Action.FailedLoadStateException : [1bB3022899d693ebAe87a42b542b42F656A6AB15, 9c7c438149d4cFD6CA70142393e0F72a78d79b23]Aborted as the game config state was failed to load.
  Stack Trace:
     at Nekoyume.Action.HackAndSlash.Execute(IAccountStateDelta states, Address signer, Int64 blockIndex, IRandom random) in /home/runner/work/lib9c/lib9c/Lib9c/Action/HackAndSlash.cs:line 216
   at Nekoyume.Action.HackAndSlash.Execute(IActionContext context) in /home/runner/work/lib9c/lib9c/Lib9c/Action/HackAndSlash.cs:line 94
   at Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip() in /home/runner/work/lib9c/lib9c/.Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs:line 106
```
I check it

2023-01-06 07:47 UTC, sonohoshi commented
> ```
> [xUnit.net 00:08:36.24]     Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip [FAIL]
>   Failed Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip [335 ms]
>   Error Message:
>    Nekoyume.Action.FailedLoadStateException : [1bB3022899d693ebAe87a42b542b42F656A6AB15, 9c7c438149d4cFD6CA70142393e0F72a78d79b23]Aborted as the game config state was failed to load.
>   Stack Trace:
>      at Nekoyume.Action.HackAndSlash.Execute(IAccountStateDelta states, Address signer, Int64 blockIndex, IRandom random) in /home/runner/work/lib9c/lib9c/Lib9c/Action/HackAndSlash.cs:line 216
>    at Nekoyume.Action.HackAndSlash.Execute(IActionContext context) in /home/runner/work/lib9c/lib9c/Lib9c/Action/HackAndSlash.cs:line 94
>    at Lib9c.Tests.Action.Scenario.RuneScenarioTest.Craft_And_Equip() in /home/runner/work/lib9c/lib9c/.Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs:line 106
> ```
> 
> I check it

Fixed it

2023-01-09 01:22 UTC, Unengine approved these changes

2023-01-09 01:25 UTC, ipdae commented on Lib9c/Action/HackAndSlash.cs
> +            if (ApStoneCount < 0
it makes must use ap stone each has action. is this correct?

2023-01-09 01:26 UTC, hskim881028 requested changes

2023-01-09 01:26 UTC, hskim881028 commented on Lib9c/Action/HackAndSlash19.cs
> +
```suggestion
CheckObsolete(BlockChain.Policy.BlockPolicySource.V100360ObsoleteIndex, context);
```

2023-01-11 01:30 UTC, ipdae approved these changes

2023-01-11 05:05 UTC, merged