development merge prepare-v100380
planetarium/lib9c pull request #1803
Opened 2023-03-15 08:34 UTC by ipdae

2023-03-15 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetarium/lib9c?pullRequest=1803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/planetarium/lib9c?pullRequest=1803) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: boscohyun<br/>:white_check_mark: ipdae<br/>:white_check_mark: Unengine<br/>:x: hskim1028<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetarium/lib9c?pullRequest=1803) it.</sub>

2023-03-16 07:43 UTC, sonohoshi requested changes

2023-03-16 07:43 UTC, sonohoshi commented on .Lib9c.Tests/Action/ItemEnhancementTest.cs
This test use `ItemEnhancement11`. it's ok?
I think it seems to use `ItemEnhancement` or ~12.

2023-03-17 01:13 UTC, ipdae commented on .Lib9c.Tests/Action/ItemEnhancementTest.cs
there is no problem because the enum value is the same, but I will fix it.

2023-03-17 01:57 UTC, sonohoshi approved these changes

2023-03-17 02:16 UTC, Unengine commented
CI is broken.

2023-03-17 03:38 UTC, merged