Features/mimisbrunnr
planetarium/lib9c pull request #227
Opened 2020-11-30 07:58 UTC by hskim881028

Added actions and sheets for  mimisbrunnr

2020-11-30 09:34 UTC, ipdae commented on Lib9c/TableData/MimisbrunnrSheet.cs
> +}
```suggestion
}

```

2020-11-30 09:41 UTC, hskim881028 commented on .Lib9c.Tests/Action/MimisbrunnrBttleTest.cs
> +}
I forgot eof again T.T

2020-11-30 10:56 UTC, hskim881028 commented on Lib9c/Action/MimisbrunnrBattle.cs
> +        public List<int> costumes;
Equipments type is guid, but costumes type is integer

2020-12-03 02:50 UTC, ipdae commented on Lib9c/Action/InvalidElementalException.cs
> +}
```suggestion
}

```

2020-12-03 12:35 UTC, hskim881028 commented on Lib9c/Action/MimisbrunnrBattle.cs
> +        public List<int> costumes;
I think it is better to fix after merging PR(https://github.com/planetarium/lib9c/pull/234/commits/7faf3b60d4b7b4b9948ff968c6e272a785b6dd7b)

2020-12-04 05:30 UTC, ipdae commented
test is roken

2020-12-04 07:50 UTC, Unengine approved these changes

2020-12-04 09:52 UTC, ipdae approved these changes

2020-12-04 09:58 UTC, boscohyun approved these changes

2020-12-04 10:35 UTC, boscohyun requested changes

2020-12-04 10:35 UTC, boscohyun commented on Lib9c/Model/State/AvatarState.cs
> +        }
```suggestion
```

https://github.com/planetarium/lib9c/blob/6eb98d42ccd4cc7bff86688af6bbb74e01c84d19/Lib9c/Model/State/AvatarState.cs#L522

2020-12-04 10:35 UTC, boscohyun commented on Lib9c/Action/MimisbrunnrBattle.cs
> +            avatarState.EquipEquipments(equipments);
```suggestion
            avatarState.EquipItems(new List<Guid>(costumes).AddRange(equipments));
```

https://github.com/planetarium/lib9c/blob/6eb98d42ccd4cc7bff86688af6bbb74e01c84d19/Lib9c/Model/State/AvatarState.cs#L522

2020-12-08 07:32 UTC, boscohyun requested changes

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            Assert.True(hackAndSlash.Result.IsClear);
These lines seems unnecessary.

```suggestion
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            Assert.True(avatarState.worldInformation.IsStageCleared(stageIdToClear));
This line seems unnecessary.

```suggestion
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            var tableCsv = _initialState.GetSheetCsv<WorldUnlockSheet>();
```suggestion
            var tableCsv = nextState.GetSheetCsv<WorldUnlockSheet>();
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            var tableCsv = _initialState.GetSheetCsv<WorldUnlockSheet>();
```suggestion
            var tableCsv = nextState.GetSheetCsv<WorldUnlockSheet>();
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            var worldUnlockSheet = _initialState.GetSheet<WorldUnlockSheet>();
```suggestion
            var worldUnlockSheet = nextState.GetSheet<WorldUnlockSheet>();
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            var newTable = new StringBuilder(tableCsv).Replace("4,2,100,10001", "4,2,80,10001").ToString();
We need to subtract the hardcoded part of this line as a factor. For example..

```suggestion
            var newTable = new StringBuilder(tableCsv).Replace(targetRowStringBefore, targetRowStringAfter).ToString();
```

2020-12-08 07:32 UTC, boscohyun commented on .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
> +            Assert.True(avatarState.worldInformation.IsWorldUnlocked(worldIdToUnlock));
These lines seems unnecessary.

```suggestion
```

2020-12-08 07:55 UTC, Unengine approved these changes

2020-12-08 08:08 UTC, hskim881028 commented on Lib9c/Battle/StageRewardExpHelper.cs
> +            if (stageNumber >= GameConfig.MimisbrunnrWorldId)
It's a miracle to go well.. I should have compared the stageId

2020-12-08 09:42 UTC, boscohyun approved these changes

2020-12-08 09:45 UTC, merged