Introduce Dispel skill
planetarium/lib9c pull request #2435
Opened 2024-03-04 02:23 UTC by U-lis

- Add `affected` to `SkillInfo` to flag current buff/debuff is affected to target.
- Update `ProcessBuff` function to add dispel effect.
- `AddBuff` function now returns `dispelList` which is list of removed skill by dispel buff.

---
This PR resolves #2389

2024-03-05 01:48 UTC, U-lis commented
리뷰 주안점
1. Dispel 은 사용 시, 지속 시 양쪽에 효과가 있다. 두개의 효과가 각각 알맞은 타이밍에 계산되는지 확인 필요.
2. Dispel 은 debuff 만 지워야 하고, buff 는 남겨야 한다. 기준은 SkillSheet 에 Debuff 로 되어 있는 것들.
    - deuff 를 찾기 위해 좀 복잡한 방법을 쓰고 있는데, 더 간결하게 할 수 있는 방법이 있을지? 
4. Arena 에서도 잘 작동하는지 확인 필요. (아레나 테스트를 만들어야 할지도)

2024-03-05 04:09 UTC, ipdae requested changes

2024-03-05 04:09 UTC, ipdae commented on Lib9c/Model/Character/CharacterBase.cs
> +                            var debuffSkillIdList = Simulator.SkillSheet.Values
시트목록을 전체조회해야하는 이유가 있는건가요? 캐릭터자체가 소유하고있는 버프 목록에서 처리하는게 불가능해서 아이디 목록같은걸 만들어야한다면 현재 구조에선 버프가 더해질때마다 전체조회를 하게 되는데, 버프아이디목록같은걸 시뮬레이터 생성자등에 옮겨서 한번만 호출하게하고 그 리스트를 참조하는게 좋아보입니다.

2024-03-05 04:09 UTC, ipdae commented on Lib9c/Model/Character/CharacterBase.cs
> +                                     ActionBuffs.Where(bf =>
StatBuffs와 ActionBuffs는 Buffs.OfType 으로 구분해놓은 필드로 보이는데 반드시 따로 처리해야하는건가요?

2024-03-05 04:48 UTC, U-lis commented on Lib9c/Model/Character/CharacterBase.cs
> +                                     ActionBuffs.Where(bf =>
StatBuff 와 ActionBuff 를 지울 때 하는 행동이 달라서 구분해놨습니다.

2024-03-06 04:12 UTC, ipdae commented on Lib9c/Model/Character/CharacterBase.cs
> +                                     ActionBuffs.Where(bf =>
RemoveBuff같은 공통 메서드를 만들고 내부 동작을 다르게 하는건 어떨까요? 지금 구조면 전체 버프 목록 조회 -> StatBuff, ActionBuff 타입 정리 -> 다시 각 버프별 루프로 이뤄지는 식인데, 버프목록을 한번만 순회하면서 내부 동작을 다르게하는걸로 단순화가 가능할것같습니다.

2024-03-06 08:17 UTC, jonny-jeahyunchoi commented on Lib9c/TableCSV/Skill/SkillSheet.csv
> +700010,면역,Normal,Buff,Buff,Self,1,15
700007,집중,Normal,Buff,Focus,Self,1,15 처럼 카테고리탭에 Dispel이 들어가야될것같습니다~!
`700010,면역,Normal,Buff,Dispel,Self,1,15`

2024-03-06 09:06 UTC, sonohoshi commented on Lib9c/Model/Character/ArenaCharacter.cs
> +        public IEnumerable<Buff.Buff> AddBuff(Buff.Buff buff, bool updateImmediate = true)
`IEnumerable<Buff.Buff>` 을 반환하게 바뀌었는데, 쭉 읽어본 바로는 Dispel로 지워질 수 있는 버프들을 모아서 반환하는건지? 좀 헷갈리는 상태입니다. 설명해주시거나, docstr을 달아서 무슨 동작을 위해 어떤걸 반환하는지 메모해주시면 좋을 것 같습니다

2024-03-06 09:08 UTC, sonohoshi commented on Lib9c/Model/Character/ArenaCharacter.cs
> +                            var debuffList = _skillBuffSheet.Values.Where(
이거 아예 Buff의 id나 skill id 같은걸 던지면 positive한 buff인지 negative한 buff인지 반환해주는 판독용 유틸 메소드 같은게 따로 있으면 더 정리가 잘될 것 같습니다.

2024-03-06 09:10 UTC, jonny-jeahyunchoi commented on Lib9c/TableCSV/Skill/SkillSheet.csv
>  700009,디버프 제거,Normal,Buff,Buff,Self,1,15
기존 디버프제거는 Dispel 스킬카테고리로 같이 변경되어야할것같습니다~!
아니면 두개가 다른 스킬인건가요?

2024-03-06 09:14 UTC, U-lis commented on Lib9c/TableCSV/Skill/SkillSheet.csv
>  700009,디버프 제거,Normal,Buff,Buff,Self,1,15
네 제가 알기로는 두개가 다른걸겁니다.
슈님께 더블체크 해봐야 할지도 모르겠네요

2024-03-06 09:31 UTC, jonny-jeahyunchoi commented on Lib9c/TableCSV/Skill/SkillSheet.csv
>  700009,디버프 제거,Normal,Buff,Buff,Self,1,15
@NineSyu 디버프제거와 면역스킬은 스킬을 지우는 Dispel 기능을 사용하되 수치밸런스로 구분하는 스킬같아보이는데요 확인 부탁드립니다~!

2024-03-07 01:40 UTC, jonny-jeahyunchoi approved these changes

2024-03-07 02:23 UTC, sonohoshi approved these changes
LGTM

2024-03-07 07:30 UTC, eugene-doobu approved these changes

2024-03-11 01:19 UTC, merged