Migrate `AvatarState.actionPoint` to use `ActionPointModule`
planetarium/lib9c pull request #2502
Opened 2024-04-01 05:56 UTC by sonohoshi

resolve #2496 

#2495 에서 변경된 ActionPoint 상태를 다른 액션에서도 반영하는 PR입니다.
변경되는 파일이 많아, 가능한 한 파일별로 변경이 생길때마다 커밋을 나눴습니다.
주로 ActionPointModule을 사용하게 변경한 커밋, 그리고 이를 단위 테스트에서 반영한 커밋으로 구분하였습니다.

이하는 액션 변경 커밋들의 설명입니다.
- 82c37f52efda34bad9008a4b7c649c77ea3d4ae0 에서 ItemEnhancement의 무의미한 actionPoint 참조를 제거
- ea5897f8a5c3bb49b5db965f0eddac7adacea228 에서 ChargeActionPoint가 ActionPointModule을 사용하도록 반영
- 10a065147216754a7c40fac24ecd60b4eef55fd4 에서 CombinationEquipment가 필요한 경우 ActionPointModule을 사용하도록 반영
- 62c6b62cf5447e6d4e938489d8a4151ec3d26bed 에서 CombinationConsumable가 필요한 경우 ActionPointModule을 사용하도록 반영
- d7b6f51184be5bc954b941491a9307f15d14162f 에서 EventConsumableItemCrafts가 필요한 경우 ActionPointModule을 사용하도록 반영
- a50cf1ac170816990c0e39f370bcc0aad75fff2a 에서 Grinding이 ActionPointModule을 사용하도록 반영
- 55822a3c38d6a82a4477668b77a00879c525ba66 에서 HackAndSlash가 ActionPointModule을 사용하도록 반영 
- 3ae2140f8ff9af4eb6960e3f644a5cf25b7f9598 에서 HAS Sweep이 ActionPointModule을 사용하도록 반영
- 3b170dd4ba283ba9367bb38095e369664558face 에서 AvatarState.UseAp() 메소드를 InventoryExtensions로 옮겨서 ActionPointModule을 사용하도록 반영
- 6a5c4f373719dc12912739c75a612075943a21b8 에서 AvatarState.UseAp()를 쓰던 부분을 모두 InventoryExtensions.UseActionPoint() 를 쓰도록 반영

2024-04-01 12:40 UTC, ipdae commented on Lib9c/Helper/InventoryExtensions.cs
> +        public static IWorld UseActionPoint(
실제 사용은 인벤토리보다는 액션안에서 IWorld를 대상으로 하는 경우가 더 많을것같은데, ActionPointModule로 옮기고 인벤토리를 받게하는건 어떨까요? 아니면 state의 변경은 별도로 처리하고 이 메서드는 인벤토리에서 ap포션을 사용하는것까지만 책임지는게 더 좋을것같습니다. (추후에 최적화를 더 진행하게 된다면 인벤토리만 변경한후 IWorld에 Set하는 경우도 있을것 같아서)

2024-04-01 12:40 UTC, ipdae commented on Lib9c/Action/ChargeActionPoint.cs
> +            var actionPoint = states.GetActionPoint(avatarAddress);
diff에는 안잡히는데 이 액션은 `UseActionPoint` 를 사용하지 않나요?

2024-04-01 12:40 UTC, ipdae commented on Lib9c/Action/CreateAvatar.cs
> +                .SetActionPoint(avatarAddress, DailyReward.ActionPointMax);
(아마 DailyReward에서 동작오류는 없겠지만) 새로 생성되는 아바타는 명시적으로`SetDailyRewardReceivedBlockIndex` 로 설정을 해주는게 좋을것같습니다.

2024-04-02 01:01 UTC, ipdae requested changes
현재 수정된 액션들은 모두 GetActionPoint를 통해 마이그레이션된 ActionPoint가 체인에 존재하는것을 전제로 작성되있는데, 실제 체인에서는 DailyReward액션을 실행하거나 신규생성된 아바타가 아니면 마이그레이션된 상태가 존재하지 않는 상태입니다. ActionPointModule.TryGetActionPoint처럼 예외처리를 통해 마이그레이션이 안된 상태면 기존 아바타의 actionPoint를 사용하고, 마지막에 반환할때 SetActionPoint를 호출해 패시브 마이그레이션이 진행되도록 고려해야합니다.

2024-04-02 01:56 UTC, sonohoshi commented on Lib9c/Helper/InventoryExtensions.cs
> +        public static IWorld UseActionPoint(
인벤토리쪽에서 AP포션을 사용하는거까지만 책임지는게 나을거같아서 그 방향으로 변경해보겠습니다.

2024-04-02 01:57 UTC, sonohoshi commented on Lib9c/Action/ChargeActionPoint.cs
> +            var actionPoint = states.GetActionPoint(avatarAddress);
네. 기존의 `UseAp()`는 ***Product 같은 아이템 판매/구매 관련 액션에서만 쓰고 있었습니다.

2024-04-02 02:01 UTC, sonohoshi commented on Lib9c/Action/CreateAvatar.cs
> +                .SetActionPoint(avatarAddress, DailyReward.ActionPointMax);
@ipdae 기존에는 `AvatarState()` 생성자쪽에서도 set을 안해서 CreateAvatar 액션 실행 이후에도 0L로 set되는 형태였는데, 명시적으로 `SetDailyRewardReceivedBlockIndex(avatarAddress, 0L)` 같은 호출을 해주는게 좋을까요?
아니면 아예 생성 시점의 인덱스를 set해주는게 좋겠다는 말씀이셨을까요?

2024-04-02 02:15 UTC, ipdae commented on Lib9c/Action/CreateAvatar.cs
> +                .SetActionPoint(avatarAddress, DailyReward.ActionPointMax);
`SetDailyRewardReceivedBlockIndex(avatarAddress, 0L)` 을 하는게 좋겠다는 얘기였습니다.

2024-04-02 02:17 UTC, sonohoshi commented on Lib9c/Action/CreateAvatar.cs
> +                .SetActionPoint(avatarAddress, DailyReward.ActionPointMax);
이해했습니다 반영하도록 하겠습니다

2024-04-02 06:29 UTC, sonohoshi commented
> 현재 수정된 액션들은 모두 GetActionPoint를 통해 마이그레이션된 ActionPoint가 체인에 존재하는것을 전제로 작성되있는데, 실제 체인에서는 DailyReward액션을 실행하거나 신규생성된 아바타가 아니면 마이그레이션된 상태가 존재하지 않는 상태입니다. ActionPointModule.TryGetActionPoint처럼 예외처리를 통해 마이그레이션이 안된 상태면 기존 아바타의 actionPoint를 사용하고, 마지막에 반환할때 SetActionPoint를 호출해 패시브 마이그레이션이 진행되도록 고려해야합니다.

@ipdae `ActionPointModule.TryGetActionPoint()` 를 만들어서 여기서 false가 나온 애들은 avatarState.actionPoint를 쓴 뒤 최종적으론 소모된 후의 값을 `ActionPointModule.SetActionPoint()` 할 수 있게 변경했습니다.
그 외엔 `InventoryExtensions.UseActionPoint()` 가 IWorld를 변경하지 않고, 아이템과 AP 사용후 남은 AP를 계산하여 반환하도록 수정했습니다. 리뷰 다시 부탁드립니다

2024-04-02 08:58 UTC, ipdae approved these changes

2024-04-02 09:13 UTC, merged