Fix buy3 action
planetarium/lib9c pull request #251
Opened 2020-12-18 13:34 UTC by ipdae

- fix missing update api in `Buy3`

2020-12-18 13:40 UTC, boscohyun approved these changes

2020-12-18 13:41 UTC, hskim881028 approved these changes

2020-12-23 02:48 UTC, boscohyun requested changes
Mail with the same block index can be a problem, so please consider this.

2020-12-23 07:07 UTC, boscohyun approved these changes

2021-01-05 02:57 UTC, boscohyun commented
--- a/Lib9c/Action/CombinationEquipment3.cs
+++ b/Lib9c/Action/CombinationEquipment4.cs
```diff
@@ -19,8 +19,8 @@ using Nekoyume.TableData;
 namespace Nekoyume.Action
 {
     [Serializable]
-    [ActionType("combination_equipment3")]
-    public class CombinationEquipment3 : GameAction
+    [ActionType("combination_equipment4")]
+    public class CombinationEquipment4 : GameAction
     {
         public static readonly Address BlacksmithAddress = ItemEnhancement.BlacksmithAddress;
 
@@ -216,7 +216,7 @@ namespace Nekoyume.Action
             var mail = new CombinationMail(result, ctx.BlockIndex, ctx.Random.GenerateRandomGuid(),
                 requiredBlockIndex);
             result.id = mail.id;
-            avatarState.UpdateV2(mail);
+            avatarState.UpdateV3(mail);
             avatarState.questList.UpdateCombinationEquipmentQuest(RecipeId);
             avatarState.UpdateFromCombination(equipment);
             avatarState.UpdateQuestRewards(materialSheet);
```

--- a/Lib9c/Action/HackAndSlash3.cs
+++ b/Lib9c/Action/HackAndSlash4.cs
```diff
@@ -15,10 +15,10 @@ using Serilog;
 namespace Nekoyume.Action
 {
     [Serializable]
-    [ActionType("hack_and_slash3")]
-    public class HackAndSlash3 : GameAction
+    [ActionType("hack_and_slash4")]
+    public class HackAndSlash4 : GameAction
     {
-        public List<int> costumes;
+        public List<Guid> costumes;
         public List<Guid> equipments;
         public List<Guid> foods;
         public int worldId;
@@ -45,7 +45,7 @@ namespace Nekoyume.Action
         protected override void LoadPlainValueInternal(
             IImmutableDictionary<string, IValue> plainValue)
         {
-            costumes =  ((List) plainValue["costumes"]).Select(e => e.ToInteger()).ToList();
+            costumes =  ((List) plainValue["costumes"]).Select(e => e.ToGuid()).ToList();
             equipments = ((List) plainValue["equipments"]).Select(e => e.ToGuid()).ToList();
             foods = ((List) plainValue["foods"]).Select(e => e.ToGuid()).ToList();
             worldId = plainValue["worldId"].ToInteger();
@@ -136,9 +136,9 @@ namespace Nekoyume.Action
                 );
             }
 
-            avatarState.ValidateEquipments(equipments, context.BlockIndex);
+            avatarState.ValidateEquipmentsV2(equipments, context.BlockIndex);
             avatarState.ValidateConsumable(foods, context.BlockIndex);
-            avatarState.ValidateCostume(new HashSet<int>(costumes));
+            avatarState.ValidateCostume(costumes);
 
             var costumeStatSheet = states.GetSheet<CostumeStatSheet>();
 
@@ -153,9 +153,8 @@ namespace Nekoyume.Action
 
             avatarState.actionPoint -= stageRow.CostAP;
 
-            avatarState.EquipCostumes(new HashSet<int>(costumes));
-
-            avatarState.EquipEquipments(equipments);
+            var items = equipments.Concat(costumes);
+            avatarState.EquipItems(items);
             sw.Stop();
             Log.Debug("HAS Unequip items: {Elapsed}", sw.Elapsed);
 
@@ -175,9 +174,9 @@ namespace Nekoyume.Action
             Log.Debug("HAS Initialize Simulator: {Elapsed}", sw.Elapsed);
 
             sw.Restart();
-            simulator.Simulate();
+            simulator.SimulateV2();
             sw.Stop();
-            Log.Debug("HAS Simulator.Simulate(): {Elapsed}", sw.Elapsed);
+            Log.Debug("HAS Simulator.SimulateV2(): {Elapsed}", sw.Elapsed);
 
             Log.Debug(
                 "Execute HackAndSlash({AvatarAddress}); worldId: {WorldId}, stageId: {StageId}, result: {Result}, " +
@@ -213,7 +212,7 @@ namespace Nekoyume.Action
             avatarState.UpdateQuestRewards(materialSheet);
 
             avatarState.updatedAt = ctx.BlockIndex;
-            avatarState.mailBox.CleanUp();
+            avatarState.mailBox.CleanUpV2();
             states = states.SetState(avatarAddress, avatarState.Serialize());
 
             sw.Stop();
```

--- a/Lib9c/Action/MimisbrunnrBattle.cs
+++ b/Lib9c/Action/MimisbrunnrBattle2.cs
```diff
@@ -16,8 +16,8 @@ using Serilog;
 namespace Nekoyume.Action
 {
     [Serializable]
-    [ActionType("mimisbrunnr_battle")]
-    public class MimisbrunnrBattle : GameAction
+    [ActionType("mimisbrunnr_battle2")]
+    public class MimisbrunnrBattle2 : GameAction
     {
         public List<Guid> costumes;
         public List<Guid> equipments;
@@ -176,7 +176,7 @@ namespace Nekoyume.Action
             sw.Stop();
             Log.Debug("Mimisbrunnr Check Equipments ElementalType: {Elapsed}", sw.Elapsed);
 
-            avatarState.ValidateEquipments(equipments, context.BlockIndex);
+            avatarState.ValidateEquipmentsV2(equipments, context.BlockIndex);
             avatarState.ValidateConsumable(foods, context.BlockIndex);
             avatarState.ValidateCostume(costumes);
             
@@ -247,7 +247,7 @@ namespace Nekoyume.Action
             avatarState.UpdateQuestRewards(materialSheet);
 
             avatarState.updatedAt = ctx.BlockIndex;
-            avatarState.mailBox.CleanUp();
+            avatarState.mailBox.CleanUpV2();
             states = states.SetState(avatarAddress, avatarState.Serialize());
 
             sw.Stop();
```

--- a/Lib9c/Action/RankingBattle2.cs
+++ b/Lib9c/Action/RankingBattle3.cs
```diff
@@ -7,6 +7,7 @@ using System.Numerics;
 using Bencodex.Types;
 using Libplanet;
 using Libplanet.Action;
+using Libplanet.Assets;
 using Nekoyume.Battle;
 using Nekoyume.Model.BattleStatus;
 using Nekoyume.Model.State;
@@ -16,8 +17,8 @@ using Serilog;
 namespace Nekoyume.Action
 {
     [Serializable]
-    [ActionType("ranking_battle2")]
-    public class RankingBattle2 : GameAction
+    [ActionType("ranking_battle3")]
+    public class RankingBattle3 : GameAction
     {
         public const int StageId = 999999;
         public static readonly BigInteger EntranceFee = 100;
@@ -25,7 +26,7 @@ namespace Nekoyume.Action
         public Address AvatarAddress;
         public Address EnemyAddress;
         public Address WeeklyArenaAddress;
-        public List<int> costumeIds;
+        public List<Guid> costumeIds;
         public List<Guid> equipmentIds;
         public List<Guid> consumableIds;
         public BattleLog Result { get; private set; }
@@ -66,13 +67,22 @@ namespace Nekoyume.Action
             Log.Debug("RankingBattle Get AgentAvatarStates: {Elapsed}", sw.Elapsed);
             sw.Restart();
 
-            avatarState.ValidateEquipments(equipmentIds, context.BlockIndex);
+            var items = equipmentIds.Concat(costumeIds);
+
+            avatarState.ValidateEquipmentsV2(equipmentIds, context.BlockIndex);
             avatarState.ValidateConsumable(consumableIds, context.BlockIndex);
+            avatarState.ValidateCostume(costumeIds);
 
             sw.Stop();
             Log.Debug("RankingBattle Validate Equipments: {Elapsed}", sw.Elapsed);
             sw.Restart();
 
+            avatarState.EquipItems(items);
+
+            sw.Stop();
+            Log.Debug("RankingBattle Equip Equipments: {Elapsed}", sw.Elapsed);
+            sw.Restart();
+
             if (!avatarState.worldInformation.TryGetUnlockedWorldByStageClearedBlockIndex(out var world) ||
                 world.StageClearedId < GameConfig.RequireClearedStageLevel.ActionsInRankingBoard)
             {
@@ -81,14 +91,6 @@ namespace Nekoyume.Action
                     world.StageClearedId);
             }
 
-            avatarState.EquipCostumes(new HashSet<int>(costumeIds));
-            avatarState.EquipEquipments(equipmentIds);
-            avatarState.ValidateCostume(new HashSet<int>(costumeIds));
-
-            sw.Stop();
-            Log.Debug("RankingBattle Equip Equipments: {Elapsed}", sw.Elapsed);
-            sw.Restart();
-
             var enemyAvatarState = states.GetAvatarState(EnemyAddress);
             if (enemyAvatarState is null)
```

2021-01-05 04:11 UTC, merged