Introduce rune level bonus
planetarium/lib9c pull request #2524
Opened 2024-04-09 19:02 UTC by U-lis

- Migrate to use RuneStateModule
- Calculate rune level bonus and add to stat

---
This PR closes #2494

2024-04-11 04:49 UTC, ipdae commented on Lib9c/Model/Stat/CharacterStats.cs
> +                ))
현재 구조는 룬레벨보너스의 곱연산이 각 옵션마다 처리되고 % 스탯에서도 영향을 받을것처럼 보이는데, 문제가 없을까요? @jaeho0103  @NineSyu

2024-04-11 04:54 UTC, jaeho0103 commented on Lib9c/Model/Stat/CharacterStats.cs
> +                ))
네 해당 부분을 고려해서 밸런싱을 하려고 해서 현재는 의도된 스펙 안의 부분입니다. 관련해서 다음주까지 시연 및 테스트등을 통해 이슈가 있을지 좀더 꼼꼼하게 체크해보도록 하겠습니다.

2024-04-12 04:49 UTC, sonohoshi commented
https://github.com/planetarium/lib9c/actions/runs/8656222360/job/23736404801?pr=2524#step:6:108
테스트가 깨졌습니다.

2024-04-12 06:00 UTC, sonohoshi requested changes

2024-04-12 06:00 UTC, sonohoshi commented on Lib9c/Model/Character/ArenaPlayerDigest.cs
> +                .Add(Runes.Serialize());
Serialize에서는 AllRuneState를 Serialize하고 Deserialize 과정에서는 그걸 그대로 List로 받아서 RuneState로 만들고있는데, 이게 AllRuneState의 의도한 사용 방식일까요?

2024-04-12 06:12 UTC, U-lis commented on Lib9c/Model/Character/ArenaPlayerDigest.cs
> +                .Add(Runes.Serialize());
어 이거 deserialize 할 때 AllRuneState 로 안 만들던가요? 그럼 수정해야 합니다

2024-04-12 06:14 UTC, sonohoshi commented on Lib9c/Model/Character/ArenaPlayerDigest.cs
> +                .Add(Runes.Serialize());
@U-lis 제가 체크했을때는 IValue 받아서 deserialize 하는 코드가 list iterate를 하는걸로 보여서, 확인 한번 해주시면 좋을거같아요

2024-04-12 06:43 UTC, U-lis commented on Lib9c/Model/Character/ArenaPlayerDigest.cs
> +                .Add(Runes.Serialize());
아 이거 `AllRuneState.Serialize()` 보시면 `Runes.Values` 를 list serialize 해줍니다.
그래서 IValue 가 `List[List[int, int]]` 로 되어 있고, deserialize 할 때는 저렇게 iterate 하면서 하나씩 `RuneState` 로 만들어서 AllRuneState 에 넣어주면 됩니다.
그러고보니 요거 serialize test 가 없는 것 같기도 하네요 추가해두겠습니다

2024-04-12 06:44 UTC, sonohoshi commented on Lib9c/Model/Character/ArenaPlayerDigest.cs
> +                .Add(Runes.Serialize());
아 그럼 AllRuneState의 Serialize 형태는 List<RuneState> 와도 같다고 볼 수 있는거군요. 이해했습니다
좀 헷갈리는거같아서 네 ㅋㅋㅋㅋ 말씀대로 Serialize 테스트 코드가 있으면 확인하기 더 쉬울 것 같네요 🙇‍♂️

2024-04-12 08:19 UTC, sonohoshi approved these changes

2024-04-16 03:27 UTC, tyrosine1153 approved these changes

2024-04-16 05:08 UTC, tyrosine1153 requested changes
104db3e5204ccf6ded0cdabd08770db3b99c36c1 에서 AllRuneState이 아닌 장착한 룬만 스탯에 적용하도록 수정을 해주셨는데, 아레나만 수정되어있고 다른 부분은 AllRuneState를 스탯으로 바로 적용하는 것 같습니다. 

예를 들어, 기존에 HAS 액션에서는 RuneInfos 값을 참고해 이번에 장착한 룬을 List<RuneState>로 만들어 StageSimulator에 전해주고 있었는데요, 수정된 경우 이번 액션에서 장착한 룬의 정보를 따로 참고하고 있지 않아보입니다.

맞는지 확인 부탁드립니다!

2024-04-16 08:23 UTC, ipdae requested changes

2024-04-16 08:23 UTC, ipdae commented on Lib9c/Action/BattleArena.cs
> +            var myRuneSlotStateAddress = RuneSlotState.DeriveAddress(myAvatarAddress, BattleType.Arena);
룬관련 마이그레이션을 생각하면 슬롯도 별도 어카운트로 분리해야되는거 아닌가 싶네요(지금 적용이 힘들면 추후에라도)

2024-04-16 08:23 UTC, ipdae commented on Lib9c/Model/Character/Player.cs
> +            foreach (var rune in runes.Runes.Values)
이쪽 코드를 봐서는 여전히 룬슬롯에 따른 필터링 처리가 안되고 있는것처럼 보이는데 확인 부탁드립니다.(애초에 인자를 착용된 룬만 넘어오게 하는게 나을것같네요.)

2024-04-16 08:25 UTC, U-lis commented on Lib9c/Model/Character/Player.cs
> +            foreach (var rune in runes.Runes.Values)
이게 저도 그렇게 하려고 했는데 이게 bonus 계산때문에 좀 전달이 깊습니다.
아예 보너스를 완전 밖에서 계산해서 주는게 맞나.. 싶기도 하네요 :thinking:

2024-04-16 08:28 UTC, ipdae commented on Lib9c/Model/Character/Player.cs
> +            foreach (var rune in runes.Runes.Values)
runeLevelBonus(allRuneState를 통한 총합의 보정치)는 뒤에서 이미 넘어오고 있으니 호출하는 쪽에서 적용될 룬(착용한 룬)만 필터링하면 될듯한데, 제가 이해를 잘못한걸까요?

2024-04-16 08:34 UTC, U-lis commented on Lib9c/Action/BattleArena.cs
> +            var myRuneSlotStateAddress = RuneSlotState.DeriveAddress(myAvatarAddress, BattleType.Arena);
네 요건 일단 이슈 하나 만들어두겠습니다.

2024-04-17 01:06 UTC, U-lis commented on Lib9c/Model/Character/Player.cs
> +            foreach (var rune in runes.Runes.Values)
아 이거 수정하면서 코드 보니까 넘기는 쪽에서 착용한 룬만 넘기게 수정은 했는데, runeSkill 이랑 runeStat 중에 하나만 고쳤었네요 둘다 착용한 룬만 받게 수정했습니다.

2024-04-17 02:23 UTC, tyrosine1153 approved these changes

2024-04-17 07:15 UTC, merged