Feature/fix frostbite effect in arena
planetarium/lib9c pull request #2626
Opened 2024-06-12 08:27 UTC by eugene-doobu

set frostbite id as group id

https://github.com/planetarium/NineChronicles/issues/5024

2024-06-14 02:06 UTC, ipdae requested changes
이러면 모든 레벨의 동상 효과가 같은 레벨로 표시될것같습니다. https://github.com/planetarium/lib9c/blob/development/Lib9c/TableCSV/Skill/StatBuffSheet.csv#L127-L129

2024-06-14 07:45 UTC, eugene-doobu commented
@ipdae 수정 후 리뷰 리퀘스트 보냈습니다

2024-06-14 09:34 UTC, ipdae approved these changes

2024-06-18 04:45 UTC, eugene-doobu commented
아래 클라이언트 pr 코드리뷰되면 그 시점에 머지 진행하겠습니다
https://github.com/planetarium/NineChronicles/pull/5050

2024-06-19 05:11 UTC, merged