Optimize ClaimAdventureBossReward action
planetarium/lib9c pull request #2651
Opened 2024-06-26 07:41 UTC by U-lis

- Iterate season in action, not in helper
- Collect methods does not need context anymore - TransferAsset moved out to action from helper
- Throw an exception when no reward to receive

2024-06-26 08:46 UTC, ipdae requested changes

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                throw new InvalidOperationException($"{AvatarAddress} has no reward to receive");
아마 기존에도 받을수있는 리워드가 없을때 사용됐던 예외가 따로 있을것같은데, 그걸 쓰거나 없다면 새로 하나 정의를 해서 쓰는게 좋을것같습니다.

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                var investor =
밑에서 Claimed를 따로 조건으로 걸고있는데 linq에서 조건으로 걸면 아래에서 is null체크로 정리가 가능할것같습니다.

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                    states = states.SetBountyBoard(szn, bountyBoard);
코드 diff만 봐서는 알수가 없는데 bountyBoard의 정보는 CollectWantedReward 내부에서 변경되는건가요?

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                if (ncgReward.RawValue > 0)
RawValue대신 0 * NCG currency를 써서 비교하는게 더 코드가 보기 쉬울것같습니다.

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                        Addresses.BountyBoard.Derive(
이건 위에서 선언한 시즌 주소와 다른걸까요?

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Data/AdventureBossGameData.cs
> +                return (NcgReward is null || ((FungibleAssetValue)NcgReward).RawValue == 0) &&
음수일때 통과할것같습니다. > 0 일때로 조건을 변경하는게 좋을것같습니다.

2024-06-26 08:46 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> -        public long Season;
시즌정보가 지워지면 렌더러입장에서 리플레이하기가 더 어려워질것같은데, 차라리 액션인자로 대상 시즌 범위를 List<int>등으로 정해서 보내주는건 어떤가요?

2024-06-26 08:52 UTC, U-lis commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                    states = states.SetBountyBoard(szn, bountyBoard);
bountyBoard 안에 Investors 가 있기 때문에 Investor 의 정보를 변경하면 bountyBoard 를 SetState 해줘야 합니다.
이거도 model 분리를 안해놔가지고 불편해진....

2024-06-26 08:55 UTC, U-lis commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> -        public long Season;
음.. 요건 구조가 좀 그래서 실제로 claim action 이 돌아봐야 대상 season 을 알 수 있습니다. 그래서 사실 현재 season 을 받는 것 자체도 별 의미가 없어서요.

2024-06-26 08:55 UTC, U-lis commented on Lib9c/Data/AdventureBossGameData.cs
> +                return (NcgReward is null || ((FungibleAssetValue)NcgReward).RawValue == 0) &&
음.. 음수일 때가 있기는 한데.. 여기에 음수가 들어가면 안되지 않나... 싶기는 하네요. 일단 조건은 추가해두겠습니다.

2024-06-26 09:46 UTC, U-lis commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                        Addresses.BountyBoard.Derive(
오 같은겁니다 합치면 되겠네요 :+1:

2024-06-26 09:48 UTC, U-lis commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> +                var investor =
음.. 요건 그렇게 정리가 되기는 하는데 뭔가 조건체크가 흩어져서 보기가 더 헷갈리는 기분이네요.
요건 걍 두는게 가독성이 더 나아 보입니다.

2024-06-27 01:40 UTC, ipdae commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> -        public long Season;
시즌정보를 남기자는건 정산받을 대상 시즌을 plainValue만 봐도 알게하자는 의도였습니다.(액션도 핵당 시즌들을 불러다 처리하고요.) 지금 구조면 정산범위를 알기 어려워질것같은데, 이건 클라이언트(dp나 유니티)쪽에서 큰 문제 없나요?

2024-06-27 06:44 UTC, U-lis commented on Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
> -        public long Season;
별도 이슈로 만들어 기획 등 확인 거쳐 필요시 작업합니다.

2024-06-27 06:44 UTC, merged