Introduce CustomEquipmentCraft action
planetarium/lib9c pull request #2697
Opened 2024-07-18 01:44 UTC by U-lis

Custom craft using drawings.

In current stage, the action does not make equipment but updates proficiency only.

2024-07-19 02:10 UTC, ipdae commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +        public int RecipeId;
들어가는 재료가 도면과 도구 조합 고정인걸로 알고있는데, 따로 레시피를 쓰는건 이유가 있는걸까요?

2024-07-19 02:10 UTC, ipdae commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +                    .Add(RecipeId).Add(SlotIndex).Add(IconId)
```suggestion
                    .Add(RecipeId)
                    .Add(SlotIndex)
                    .Add(IconId)
```

2024-07-19 02:10 UTC, ipdae commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +            var agentState = states.GetAgentState(context.Signer);
따로 에이전트 스테이트를 쓰고있는 부분이 안보이는데, 지워도 될것같습니다.

2024-07-23 06:26 UTC, U-lis commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +            var agentState = states.GetAgentState(context.Signer);
아 이건 일단 장비 제작 action 의 validation 부분 다 일단 들고온거라 나중에 정리 예정입니다.

2024-07-23 07:08 UTC, U-lis commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +        public int RecipeId;
기획 체크 받아서 어떤거 쓸 지 정하기로 했습니다.

2024-07-23 07:17 UTC, sonohoshi commented on Lib9c/Model/State/AvatarState.cs
> +        public int Proficiency;
ProficiencyModule이 있으니까 이제 필요없지않나요?

2024-07-24 05:28 UTC, sonohoshi requested changes
@U-lis Proficiency가 Module로 나갔으니까 이번 PR에서 AvatarState.Proficiency만 빼주시면 다른건 괜찮을 것 같습니다.
지금 그대로 가져가서 쓰다가 나중에 지워지면 클라이언트에서 raw state를 가져와서 Serialize/Deserialize 수정을 두번 해야 할 것 같습니다.

2024-07-24 05:52 UTC, sonohoshi approved these changes

2024-07-24 05:52 UTC, merged