Update custom craft logic
planetarium/lib9c pull request #2724
Opened 2024-08-02 05:45 UTC by U-lis

- Change CSV values from decimal to long
- Move cost calculation logic to new helper
- Select item's elemental randomly
- Refactoring

2024-08-02 09:37 UTC, sonohoshi requested changes
@U-lis 변경사항은 확인했고, 유니티에서 컴파일이 안되는 부분을 우선 수정해주셔야 할 것 같습니다.

2024-08-02 09:37 UTC, sonohoshi commented on Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
> +                var elementalList = Enum.GetValues<ElementalType>();
```suggestion
                var elementalList = Enum.GetValues(typeof(ElementalType));
```
유니티에서는 `Enum.GetValues<T>()` 를 지원하지 않아서 (아마 닷넷 버전 차이인듯) typeof를 쓰는 형태로 바꿔주셔야 유니티에서도 컴파일이 됩니다.

2024-08-06 02:09 UTC, merged

2024-08-07 02:25 UTC, ipdae commented on Lib9c/Helper/CustomCraftHelper.cs
> +            if (costRow is not null)
costRow가 null인 케이스는 어떤 케이스인가요? 만약 추가 코스트 개념이라면 시트의 이름을 변경하는게 좋을것 같습니다.

2024-08-07 02:25 UTC, ipdae commented on Lib9c/Helper/CustomCraftHelper.cs
> +                (int)Math.Floor(recipeRow.DrawingAmount * relationshipRow.CostMultiplier / 10000m);
relationShip 의 해당 필드들은 long인데 타입변환을 int로 하면 데이터가 유실될 가능성은 없을까요?

2024-08-07 02:30 UTC, U-lis commented on Lib9c/Helper/CustomCraftHelper.cs
> +            if (costRow is not null)
네 특정 상황에서만 들어가는 추가 cost 입니다.
아 이게 이름에 relationship 이라거나 하는게 없군요 요건 헷갈릴 수 있으니 변경하겠습니다

2024-08-07 02:32 UTC, U-lis commented on Lib9c/Helper/CustomCraftHelper.cs
> +                (int)Math.Floor(recipeRow.DrawingAmount * relationshipRow.CostMultiplier / 10000m);
multiplier 들이 long 이기는 한데, 사실 만분율로 계산될거라 결과를 int로 변환하는건 별 이슈 없을거라고 생각하긴 했습니다