Update Grinding: add materials
planetarium/lib9c pull request #2735
Opened 2024-08-06 14:18 UTC by tyrosine1153

- resolve https://github.com/planetarium/lib9c/issues/2688
- To do
  - [x] Check material rewards in GrindingTest
  - [x] Fill test cases in CalculateMaterialReward test code

2024-08-07 02:11 UTC, ipdae requested changes

2024-08-07 02:11 UTC, ipdae commented on Lib9c/Helper/CrystalCalculator.cs
> +        public static Dictionary<Material, int> CalculateMaterialReward(
계산을 하는건 Material인데 이 메서드는 CrystalCalculator에 있어서 위치가 좀 어색한것같습니다. CrystalEquipmentGrindingSheet의 확장 메서드로 옮기면 어떨까요.

2024-08-07 02:11 UTC, ipdae commented on Lib9c/TableData/Crystal/CrystalEquipmentGrindingSheet.cs
> +                    if (!TryParseInt(fields[3 + offset], out var materialId) || materialId == 0)
material 관련정보가 패치되기전엔 테이블을 파싱하다 index 관련 오류가 발생할것같습니다. fields의 길이를 확인하면 좋을것 같습니다.

2024-08-07 02:11 UTC, ipdae commented on Lib9c/Model/Mail/GrindingMail.cs
> +            RewardMaterialCount = serialized["rmc"].ToInteger();
이전에 직렬화된 GrindingMail의 경우엔 rmc 키가 없어서 해석하다 오류가 날것같습니다. 해당 키가 있을때만 설정하도록 예외처리가 필요해보입니다.

2024-08-07 02:11 UTC, ipdae commented on Lib9c/Model/Mail/GrindingMail.cs
> +            .Add("rmc", RewardMaterialCount.Serialize());
```suggestion
            .Add("rmc", RewardMaterialCount);
```

2024-08-07 02:11 UTC, ipdae commented on Lib9c/Model/Mail/GrindingMail.cs
> +            RewardMaterialCount = serialized["rmc"].ToInteger();
```suggestion
            RewardMaterialCount = (Integer)serialized["rmc"];
```

2024-08-07 05:11 UTC, tyrosine1153 commented on Lib9c/Model/Mail/GrindingMail.cs
> +            RewardMaterialCount = serialized["rmc"].ToInteger();
ToInteger 변활과 Integer 자료형으로 변환하는 데에 어떤 차이가 있나요?

2024-08-07 06:25 UTC, ipdae commented on Lib9c/Model/Mail/GrindingMail.cs
> +            RewardMaterialCount = serialized["rmc"].ToInteger();
ToInteger가 9c 초기에 숫자타입들을 문자열로 직렬화해서 사용한 레거시입니다. 지금은 long이나 int 타입을 직렬화할때 따로 형변환을 해주지않아도 알아서 Bencodex.Integer로 직렬화가 되기때문에 사용을 지양하고 있습니다.

2024-08-08 13:30 UTC, merged

2024-08-09 02:28 UTC, ipdae reviewed
LGTM