apply all open action
planetarium/lib9c pull request #2765
Opened 2024-08-19 07:09 UTC by eugene-doobu

테스트 코드와 클라 코드 대응이 필요합니다. 현재 상태에서 CI는 깨질 것이라 draft처리 해둡니다

all open기능을 추가하기 위해 기존 RapidCombination에서 사용하던 slotIndex를 list형태로 변경하였습니다.

2024-08-21 06:47 UTC, ipdae requested changes
Sheet

2024-08-21 06:47 UTC, ipdae commented on Lib9c/Action/RapidCombination.cs
> +            _slotFlag = (Integer)plainValue["s"];
직렬화타입이 이상한것같습니다. `Bencodex.Types.List` 로 감싼 `Integer`의 목록이 되야할것같습니다.

2024-08-21 06:47 UTC, ipdae commented on Lib9c/Action/RapidCombination.cs
> +                var materialItemSheet = states.GetSheet<MaterialItemSheet>();
시트들은 메서드 인자로 받으면 GetSheet를 한번만 불러도 될것같습니다.

2024-08-22 02:04 UTC, eugene-doobu commented on Lib9c/Action/RapidCombination.cs
> +            _slotFlag = (Integer)plainValue["s"];
flag형태로 저장되게 구현해놨습니다

2024-08-26 08:11 UTC, eugene-doobu commented on Lib9c/Action/RapidCombination.cs
> +                var materialItemSheet = states.GetSheet<MaterialItemSheet>();
400fc06692f51bbc6c43369060ca2650f96605a7 여기서 수정하였습니다

2024-08-26 08:11 UTC, eugene-doobu commented on Lib9c/Action/RapidCombination.cs
> +            _slotFlag = (Integer)plainValue["s"];
1f6b707061b6158bff5a0cb11e3e9138022701d2 다음과 같이 수정하였습니다

2024-08-27 01:52 UTC, ipdae approved these changes

2024-08-27 02:06 UTC, merged