feat: introduce `ArenaParticipant` and apply to `JoinArena` first
planetarium/lib9c pull request #2823
Opened 2024-09-11 06:30 UTC by boscohyun

# Background

The `ArenaParticipant` type and its corresponding account (IAccount) were created to address the issue where Arena participant information was split across multiple addresses and too many status queries were made each time, for example, to calculate the CP of an Arena participant.

# Concern

Arenas are non-stop, so we didn't change any of the states we already created and use, such as `ArenaScore`, `ArenaInformation`, and `ArenaAvatarState`, but we did configure and synchronize the `ArenaParticipant` state to replace them going forward, which will dramatically reduce a lot of the state lookups and operations we used to do to configure Arena information.

First, I'm proposing changes to the `JoinArena` action, followed by changes to the `BattleArena` action.

# Changes

- Add `Nekoyume.Addresses.ArenaParticipant` address.
- Add `Nekoyume.Model.Arena.ArenaParticipant` with tests.
- Add `AvatarState.GetPortraitId()` method.
- Add exceptions: `UnsupportedStateException`, `AlreadyJoinedArenaException`
- Add `ArenaModule`.
- Check and set `ArenaParticipant` state in `JoinArena`.

2024-09-11 09:17 UTC, ipdae requested changes
완결성을 위해 BattleArena에서의 처리도 이 PR에서 함께 하는게 좋을것 같습니다.

2024-09-11 09:17 UTC, ipdae commented on Lib9c/Model/Arena/ArenaParticipant.cs
> +        private const string StateTypeName = "arena_participant";
별도 어카운트에 고정되서 저장되니 이 필드는 필요없는것같습니다.

2024-09-11 09:17 UTC, ipdae commented on Lib9c/Model/Arena/ArenaParticipant.cs
> +        public long LastBattleBlockIndex;
아레나 목록에선 표시안되는 정보들이 포함되있는것 같습니다. 이 필드들은 왜 저장되는걸까요?

2024-09-11 09:27 UTC, ipdae commented
가능하면 State의 주소를 유도하는 방식보단, 어카운트 주소를 시즌별로 나누고 해당 State의 주소는 AvatarAddress를 그대로 쓸수있으면 좋을 것 같습니다.

2024-09-11 09:29 UTC, boscohyun commented on Lib9c/Model/Arena/ArenaParticipant.cs
> +        public long LastBattleBlockIndex;
잘 짚어주셨습니다. 새로 추가되는 이 모델에는 아직 아레나 목록에 표시되고 있지 않은 정보 또한 포함되어 있습니다.
예를 들면 ArenaInformation이 포함하고 있던 티켓 정보나, ArenaAvatarState가 포함하고 있던 LastBattleBlockIndex와 같은 값들입니다.
저는 이번에 이 새로운 모델을 추가하면서 **아레나 참자가 정보**가 너무 여러 상태에 나뉘어 저장되고 있는 점을 함께 해소할 수 있는 여건을 마련하고 제안드리고 싶었습니다. 이렇게 추가된 정보들은 당장에는 중복 저장 이상의 의미는 없습니다만, 조금 이후에는 위에서 말씀드린 여러 타입들을 제거하고 `ArenaParticipant` 타입 하나로 참가자의 정보를 다룰 수 있기를 희망합니다. 이를 위해서 미리 초석을 마련한 것으로 봐주시면 감사하겠습니다.

2024-09-11 09:31 UTC, boscohyun commented
> 가능하면 State의 주소를 유도하는 방식보단, 어카운트 주소를 시즌별로 나누고 해당 State의 주소는 AvatarAddress를 그대로 쓸수있으면 좋을 것 같습니다. https://github.com/planetarium/lib9c/blob/development/Lib9c/Module/AdventureBossModule.cs 를 참고해보시면 될것같습니다.

참고해보겠습니다.

2024-09-11 09:32 UTC, boscohyun commented
> 완결성을 위해 BattleArena에서의 처리도 이 PR에서 함께 하는게 좋을것 같습니다.

이 코멘트가 올라오기 조금 전에 분리한 PR이 올라갔는데요. 해당 PR을 닫고 이곳에 포함시키겠습니다.

2024-09-11 09:37 UTC, boscohyun commented
@ipdae 추가로, 이 변경은 상태 이주를 고려하지 않고, 현행 라운드 중간에 끼어들어가도 동작하게 작성되어 있습니다. 신규 라운드가 시작된 이후에는 적절한 변경을 통해서 불필요한 로드를 줄일 수 있습니다.

2024-09-11 09:56 UTC, boscohyun commented
> 가능하면 State의 주소를 유도하는 방식보단, 어카운트 주소를 시즌별로 나누고 해당 State의 주소는 AvatarAddress를 그대로 쓸수있으면 좋을 것 같습니다. https://github.com/planetarium/lib9c/blob/development/Lib9c/Module/AdventureBossModule.cs 를 참고해보시면 될것같습니다.

안내해주신 구현을 보면, 어드벤쳐 보스의 시즌 정보는 Addresses.AdventureBoss 주소의 한 어카운트 내에서 latest(0x0...00), 시즌 1(0x0...01), 시즌 2(0x0...02) 등으로 개별 상태 주소를 특정해서 사용하고 있네요.
아레나에 그대로 대입하는 아이디어는 떠오르는 게 없고, 예를 들어서 어카운트의 주소를 챔피언십 1의 라운드 1은 0x1...000101, 챔피언십 999의 라운드 3은 0x1...099903 식으로 예약해서 사용하자는 의견이시죠?

2024-09-11 11:06 UTC, boscohyun commented
@ipdae 제안해주신 내용들 작업해봤습니다.

2024-09-11 12:40 UTC, ipdae requested changes

2024-09-11 12:40 UTC, ipdae commented on Lib9c/Action/BattleArena.cs
> +                };
기존엔 본인이 서명한 BattleArena에서만 해당 정보를 업데이트하고 있었는데 이렇게 되면 다른 사람이 내 아바타를 대상으로 실행할때도 이값들이 갱신되게 됩니다. cp, score정도만 값을 갱신하도록 변경해야할것 같습니다.

2024-09-11 12:40 UTC, ipdae commented on Lib9c/Action/BattleArena.cs
> +                {
대상 룬장착정보만 다를뿐 같은일을 반복하는것 같습니다. 메서드로 묶어서 중복을 줄이는게 좋을 것 같습니다.

2024-09-12 02:00 UTC, boscohyun commented on Lib9c/Action/BattleArena.cs
> +                };
가리키신 부분은 현행 라운드 중간에 끼워 동작하게 작성한 곳인데요. `JoinArena`를 거치지 않아서 `ArenaParticipant` 상태가 없는 경우에만 새로 넣어주고 있습니다.
그런데 생각해보니, **현행 라운드 중간부터 동작하게** 작성한 것이 애매한 걸 알게 됐습니다. 코드를 수정해서 `JoinArena`부터 `ArenaParticipant` 상태를 생성해서 들어온 경우에만 `BattleArena`에서 업데이트 시키도록 변경하겠습니다.

2024-09-12 03:35 UTC, boscohyun commented on Lib9c/Action/BattleArena.cs
> +                };
905b90e 커밋에서 불필요한 부분을 삭제해봤습니다.

2024-09-12 04:55 UTC, ipdae commented on Lib9c/Action/BattleArena.cs
> +                    enemyArenaParticipantList);
ArenaParticipant class가 업데이트될 경우 (필드가 추가된다던지)를 생각하면 조금 위험해보입니다. 역직렬화를 한다음  명시적으로 score를 업데이트시키면 어떨까요?

2024-09-12 04:55 UTC, ipdae commented on Lib9c/Exceptions/BencodexTypesExtensions.cs
> +        public static List InsertTo(this List list, int index, IValue value)
메서드명과 동작이 일치하지 않는것 같습니다. 실제동작은 Replace처럼 보입니다.

2024-09-12 05:09 UTC, boscohyun commented on Lib9c/Action/BattleArena.cs
> +                    enemyArenaParticipantList);
기존 코드가 그렇게 돼있었는데, 역직렬화 비용을 아껴볼까 하고 수정해봤는데요. 인덱스로 값을 변경하는 게 액션 맥락 밖에서의 변화에 취약해지는 면이 있네요. 되돌려 놓겠습니다.

2024-09-12 06:51 UTC, ipdae approved these changes

2024-09-12 12:26 UTC, merged