update worldboss reward
planetarium/lib9c pull request #2826
Opened 2024-09-12 05:55 UTC by tyrosine1153

2024-09-12 11:11 UTC, ipdae requested changes

2024-09-12 11:11 UTC, ipdae commented on Lib9c/Action/ClaimRaidReward.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress);
아바타의 인벤토리만 변경시키는것처럼 보이는데, `GetAvatarState`에서 `getInventory`만 `true`로 설정하고 나머지는 `false`로 호출하거나, `GetInventory`로 인벤토리만 불러와도 될것같습니다.

2024-09-12 11:11 UTC, ipdae commented on Lib9c/Action/ClaimWordBossKillReward.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress);
이쪽도 인벤토리만 불러오는 식으로 최적화가 가능할것같습니다.

2024-09-12 11:11 UTC, ipdae commented on Lib9c/Module/LegacyModule.cs
> +                    avatarState.inventory.AddItem(reward.Key, reward.Value);
인벤토리에 아이템을 더했는데, SetState를 호출하지 않고 있습니다. 인벤토리가 변경되지 않을것같습니다.

2024-09-13 02:23 UTC, tyrosine1153 commented on Lib9c/Battle/RaidSimulator.cs
> +            }
material은 itembase라 아이템 종류에 관한 정보만 있고, count에 대한 값도 같이 있는건 item일겁니다.

2024-09-13 02:31 UTC, ipdae commented
@tyrosine1153 빌드가 깨지는것 같습니다.

2024-09-13 02:52 UTC, ipdae approved these changes

2024-09-13 02:52 UTC, merged