merge development to 1.18.0 (optimize action)
planetarium/lib9c pull request #2846
Opened 2024-09-24 04:38 UTC by eugene-doobu

for optimize action

2024-09-24 04:43 UTC, ipdae requested changes
이 PR의 변경사항과는 직접적으로 관련이 없지만 `UnlockCombinationSlot` 액션 내부에서 context.Signer와 agentAddress가 동일한지에 대한 검증이 없는것 같습니다. 악용될 여지가 있으니 이 부분을 추가해야할 것 같습니다.

2024-09-24 05:16 UTC, eugene-doobu commented
https://github.com/planetarium/lib9c/issues/2848 해당 pr dev로 머지 후 open하겠습니다 

https://github.com/planetarium/lib9c/pull/2846#pullrequestreview-2324014135

2024-09-25 08:22 UTC, sonohoshi approved these changes

2024-09-25 08:23 UTC, U-lis approved these changes

2024-09-25 08:28 UTC, ipdae approved these changes

2024-09-25 08:29 UTC, merged