Introduce CostumeSummon and etc.
planetarium/lib9c pull request #2904
Opened 2024-10-16 09:29 UTC by sonohoshi

- CostumeSummon 이라는 액션을 추가했습니다. 풀코스튬과 칭호를 소환합니다.
- 기존의 ***Summon 액션들이 최대 100회까지 돌릴 수 있게 작업했습니다. 이에 맞춰 테스트를 수정하고, 10회당 +1을 해주는 로직을 추가했습니다.

resolve #2889

2024-10-17 10:26 UTC, U-lis requested changes

2024-10-17 10:26 UTC, U-lis commented on .Lib9c.Tests/Action/Summon/CostumeSummonTest.cs
> +        }
요건 `SummonSheetTest.cs` 에 연관 테스트가 있는 것 같은데, 테스트를 추가하시려면 그쪽이 더 맞을 것 같습니다

2024-10-17 10:26 UTC, U-lis commented on Lib9c/Action/CostumeSummon.cs
> +                [SummonCountKey] = SummonCount.Serialize(),
int 타입 값은 넣을 때 `Serialize()` 하지 않고, 꺼낼 때 `ToInteger()` 대신 `(Integer)` casting 을 쓰는게 올바른 사용방법이라고 배웠습니다

2024-10-17 10:34 UTC, sonohoshi commented on .Lib9c.Tests/Action/Summon/CostumeSummonTest.cs
> +        }
복붙하면서 딸려온 것 같은데, 확인해보고 알맞은쪽으로 옮겨놓겠습니다

2024-10-17 10:34 UTC, sonohoshi commented on Lib9c/Action/CostumeSummon.cs
> +                [SummonCountKey] = SummonCount.Serialize(),
이것도 복붙하면서 딸려온 모양인데ㅋㅋㅋㅋ 수정해놓겠습니다

2024-10-17 11:15 UTC, ipdae commented on Lib9c/Action/AuraSummon.cs
> +        private static readonly int[] SummonLimit = {1, 10, 100};
허용 소환횟수인건데, `AllowedSummonCount` 같은 이름으로 변경하는게 더 좋을것 같습니다.

2024-10-17 11:15 UTC, ipdae commented on Lib9c/Action/CostumeSummon.cs
> +            if (summonCount >= 10)
횟수관련 코드가 전체적으로 중복으로 복붙된 코드 같은데 소환에서 중복되는 코드들을 모아다 공통 메서드를 만드는게 어떨까 싶습니다.(SummonHelper같은 클래스로 묶는식으로)

2024-10-17 11:21 UTC, sonohoshi commented on Lib9c/Action/CostumeSummon.cs
> +            if (summonCount >= 10)
그런거같네요 한번 정리해보겠습니다

2024-10-18 01:21 UTC, ipdae commented
테스트가 깨지는것같습니다.

2024-10-18 02:19 UTC, sonohoshi commented
> 테스트가 깨지는것같습니다.

코드에 뭐 실수한 부분이 있어서 고장나는거였고 고쳤습니다

2024-10-18 02:33 UTC, ipdae approved these changes

2024-10-18 07:35 UTC, merged