Feature/claim one time gift
planetarium/lib9c pull request #2982
Opened 2024-11-05 19:34 UTC by tyrosine1153

2024-11-06 08:26 UTC, eugene-doobu approved these changes

2024-11-06 08:26 UTC, eugene-doobu commented on Lib9c/Action/ClaimGifts.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress,
Signer체크 의도적으로 빠진걸까요? 그래도 된다고 생각하지만 혹시 해서 확인 요청 드려봅니다

2024-11-06 12:31 UTC, eugene-doobu commented on Lib9c/Action/ClaimGifts.cs
> +            {
예외 등에 대해서 테스트코드 추가도 부탁드립니다

2024-11-07 06:33 UTC, ipdae commented on Lib9c/Action/ClaimGifts.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress,
아바타를 전부 가져올 필요없이 인벤토리만 들고와도 될것같습니다.

2024-11-07 06:36 UTC, ipdae commented on Lib9c/Action/ClaimGifts.cs
> +                .Add(AvatarAddressKey, AvatarAddress.Serialize())
이 키는 어디서 얻어오는건가요?

2024-11-08 10:32 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +                .Add(AvatarAddressKey, AvatarAddress.Serialize())
SerializeKeys 에서 받아오고 있습니다.
```
using static Lib9c.SerializeKeys;
```

2024-11-08 10:48 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +            {
https://github.com/planetarium/lib9c/pull/2982/commits/3c8be62d0233aecd7622e5a0550a9501b11a3608
Exception과 관련한 테스트 코드 추가했습니다.

2024-11-08 12:00 UTC, eugene-doobu commented on Lib9c/Action/ClaimGifts.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress,
### SweepAdventureBoss.cs
``` 
            var avatarState = states.GetAvatarState(AvatarAddress, true, false, false);
            if (avatarState is null || !avatarState.agentAddress.Equals(context.Signer))
            {
                throw new FailedLoadStateException($"{addressesHex}Aborted as the avatar state of the signer was failed to load.");
            }
```
avatarState.agentAddress.Equals(context.Signer) 체크부분입니다. @ipdae 님이 말씀하신 인벤토리만 가져오는것도 이거 참고하면 될 것 같습니다

2024-11-08 12:26 UTC, moreal commented on Lib9c/Module/GiftModule.cs
> +            return world.SetAccount(Addresses.ClaimedGiftIds, account);
`MutateAccount` 를 활용하면 위 `GetAccount` → `SetAccount` 하는 과정을 쉽게 할 수 있습니다.

```suggestion
            return world.MutateAccount(
                Addresses.ClaimedGiftIds,
                account => account.SetState(
                    avatarAddress,
                    claimedGiftIds.Aggregate(List.Empty, (current, giftId) => current.Add((Integer)giftId))
                )
            );
```

2024-11-08 12:26 UTC, moreal commented on Lib9c/Action/ClaimOneTimeGiftException.cs
파일명과 예외 이름이 일치 하지 않는 것 같습니다. 각 예외 별로 파일을 분리하면서 이름을 맞춰주실수 있을까요? 예외에 해당하는 소스코드 파일을 찾을때 도움이 될 것 같습니다.

2024-11-11 12:07 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +            var avatarState = states.GetAvatarState(AvatarAddress,
앗 인벤토리만 가져오도록 수정한건 이렇게 바꾸었습니다. https://github.com/planetarium/lib9c/pull/2982/commits/d371e6341cbb52f4e485a3e51a463927693b1ae1
AvatarState까지 가져올 필요 없이 Inventory 상태만 가져오도록 바꾼건데요, 좀 더 찾아보니 `Addresses.CheckAvatarAddrIsContainedInAgent` 라는 메서드로 상태 안 불러오고 AvatarAddress로 AgentAddress 확인할 수 있어서 이걸로 수정해봤습니다. https://github.com/planetarium/lib9c/pull/2982/commits/740a638ed80cb132e5169fab2c2d03da2c9c3dd0

2024-11-11 12:18 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +        public int GiftId;
LoadPlainValueInternal 에서 필드를 수정하는 경우가 있어서 readonly는 못하고 private set인 property로 수정했습니다. https://github.com/planetarium/lib9c/pull/2982/commits/088ae4440a79c60e31c197e5cfb4ea192c82fa2a

2024-11-12 01:10 UTC, sonohoshi commented
@tyrosine1153 https://github.com/planetarium/lib9c/actions/runs/11780046334/job/32809803770?pr=2982#step:7:270 유닛테스트에 실패하는게 있는거같습니다. mead 관련 코드가 정상적으로 작성되지 않은걸로 보입니다

2024-11-12 01:57 UTC, tyrosine1153 commented
> @tyrosine1153 https://github.com/planetarium/lib9c/actions/runs/11780046334/job/32809803770?pr=2982#step:7:270 유닛테스트에 실패하는게 있는거같습니다. mead 관련 코드가 정상적으로 작성되지 않은걸로 보입니다

수정했습니다. 감사합니다!

2024-11-12 02:12 UTC, ipdae requested changes

2024-11-12 02:12 UTC, ipdae commented on Lib9c/Action/ClaimGifts.cs
> +                    ? ItemFactory.CreateTradableMaterial(materialItemRow)
거래가능한 아이템을 고정적으로 주는데, 이건 맞는 스펙인가요?

2024-11-12 02:12 UTC, ipdae commented on Lib9c/Action/ClaimGifts.cs
> +                    : ItemFactory.CreateItem(itemRow, random);
NonFungibleItem(장비, 코스튬 등)을 생성하는 경우엔 아이템의 생성도 quantity만큼 돌면서 다르게 만들어야할것같습니다.(GuId가 달라야하기 때문) 완전히 똑같은건 아니지만 ClaimItems의 아이템 생성부분을 참고하시면 좋을것 같습니다.

2024-11-12 02:14 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +                    ? ItemFactory.CreateTradableMaterial(materialItemRow)
넵 재호님께 기획 확인한 대로면, 재료 아이템을 포함한 액션에서 나오는 아이템은 모두 거래 가능한게 스펙입니다.
https://planetariumhq.slack.com/archives/C07Q9CF1A1M/p1731060680696799

2024-11-12 02:21 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +                    : ItemFactory.CreateItem(itemRow, random);
https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/ClaimItems.cs#L130
이부분 말씀이신가요? ClaimItems에서도 같은 guid를 여러번 만들고 있는데... 나중에 이쪽 액션도 수정이 필요할 것 같습니다.

2024-11-12 02:56 UTC, tyrosine1153 commented on Lib9c/Action/ClaimGifts.cs
> +                    : ItemFactory.CreateItem(itemRow, random);
수정했습니다! https://github.com/planetarium/lib9c/pull/2982/commits/3fda61c2378853b872283ad1940779fa0ba6b8c3

2024-11-12 06:02 UTC, ipdae approved these changes

2024-11-12 08:53 UTC, merged