Feature/synthesize item
planetarium/lib9c pull request #3001
Opened 2024-11-14 09:34 UTC by eugene-doobu

synthesize item

https://www.notion.so/planetarium/Synthesize-13ded889905f809ebc0def2b45945090

2024-11-25 09:27 UTC, ipdae commented
@eugene-doobu 이 PR은 언제 다시 열리는걸까요?

2024-11-26 07:15 UTC, eugene-doobu commented on Lib9c/TableData/Item/SynthesizeSheet.cs
> +            public float SucceedRate { get; private set; }
76e3528d2577700c769ec1c04f5388af4c2e53c6 에서 적용해두었습니다

2024-11-27 02:19 UTC, ipdae requested changes
지금은 재료에 대한 검증 및 삭제 처리보다 합성을 먼저 처리하고 있는것 처럼 보입니다. 순서를 바꿔서 검증을 통해 조건이 안맞는 경우 우선 실패하도록 처리해야합니다.

2024-11-27 02:19 UTC, ipdae commented on Lib9c/Action/Synthesize.cs
> +                    if (!synthesizeSheet.TryGetValue(gradeId, out var synthesizeRow))
이 gradeId는 루프안에서 변경되는 정보가 아닌것 같습니다. 윗라인으로 옮겨서 호출횟수를 줄일 수 있을것 같습니다.

2024-11-27 02:19 UTC, ipdae commented on Lib9c/Action/Synthesize.cs
> +            float cumulativeWeight = 0;
float이 아니라 decimal이나 만분율을 써야할 것 같습니다. 성능문제때문에 가급적이면 만분율을 추천합니다.

2024-11-27 02:19 UTC, ipdae commented on Lib9c/Action/Synthesize.cs
> +        private float GetRandomValueForItem(Grade grade, HashSet<int> synthesizeResultPool, SynthesizeWeightSheet synthesizeWeightSheet,
이쪽도 반환타입이 float이면 안됩니다.

2024-11-27 02:19 UTC, ipdae commented on Lib9c/Action/Synthesize.cs
> +        private const string ChargeApKey = "c";
실제 ap충전 동작이 구현안되있는것 같습니다. (ap포션 사용처리)

2024-11-27 02:56 UTC, eugene-doobu commented
아이템 해제 순서 변경했습니다 @ipdae 
[4d11831](https://github.com/planetarium/lib9c/pull/3001/commits/4d11831fd4c35cbec4a8828b0cd0961b734494cd)

2024-11-27 04:29 UTC, eugene-doobu commented on Lib9c/Action/Synthesize.cs
> +                    if (!synthesizeSheet.TryGetValue(gradeId, out var synthesizeRow))
아래 커밋에서 수정했습니다
bf33ba9aa406c8e99cc1ca2587b896853e0bf21e

2024-11-27 04:31 UTC, eugene-doobu commented on Lib9c/Action/Synthesize.cs
> +        private const string ChargeApKey = "c";
아래 커밋에서 구현했습니다. 별도 pr로 뺄까 하다가 구현하기 쉬워보여서 같이 넣자 하고 삽 떠볼려고 필드만 먼저 추가해놨었습니당..
bf33ba9aa406c8e99cc1ca2587b896853e0bf21e

2024-11-27 06:10 UTC, eugene-doobu commented on Lib9c/Action/Synthesize.cs
> +            float cumulativeWeight = 0;
아래 pr에서 변경했습니다
https://github.com/planetarium/lib9c/pull/3001/commits/6a6a08e84048fbd3d2a0496ef1f47bcb10529ec2
https://github.com/planetarium/lib9c/pull/3001/commits/6b18bf334ce2c50b106f4ab8f2df264cd054efc9

2024-11-27 06:10 UTC, eugene-doobu commented on Lib9c/Action/Synthesize.cs
> +        private float GetRandomValueForItem(Grade grade, HashSet<int> synthesizeResultPool, SynthesizeWeightSheet synthesizeWeightSheet,
아래 pr에서 변경했습니다
https://github.com/planetarium/lib9c/pull/3001/commits/6a6a08e84048fbd3d2a0496ef1f47bcb10529ec2
https://github.com/planetarium/lib9c/pull/3001/commits/6b18bf334ce2c50b106f4ab8f2df264cd054efc9

2024-11-27 06:25 UTC, eugene-doobu commented on Lib9c/TableData/Item/SynthesizeSheet.cs
> +            public float SucceedRate { get; private set; }
아래 pr에서 다시 int로 변경하였습니다. 
[a472a34](https://github.com/planetarium/lib9c/pull/3001/commits/a472a346c0f046775b28fcce81f5e0404e6a514d)

2024-11-27 06:53 UTC, ipdae approved these changes

2024-11-27 06:53 UTC, ipdae commented on Lib9c/Action/Synthesize.cs
> +                        var isSuccess = random.Next(SynthesizeSheet.SucceedRateMax) < synthesizeRow.SucceedRate;
`<=, <` 중에 어떤게 맞는걸까요? 관련 주석을 추가하면 좋을것같습니다.

2024-11-27 07:18 UTC, eugene-doobu commented
@ipdae 주석은 추가해두었지만, 해당 케이스의 경우 굳이 summary주석 업데이트가 필요없는 케이스였던걸로 보여서 항상 체크할 필요는 없을 것 같습니다.
별도로 마지막 아이템이 나올 확률이 살짝 적어질 수 있는 문제가 있어보여 수정해두었습니다.
[3274722](https://github.com/planetarium/lib9c/pull/3001/commits/3274722638bd13d18c093c66200bfd61c7c2f91f)

2024-11-27 07:18 UTC, eugene-doobu commented on Lib9c/Action/Synthesize.cs
> +                        var isSuccess = random.Next(SynthesizeSheet.SucceedRateMax) < synthesizeRow.SucceedRate;
아래 pr에서 추가해두었습니다
[3274722](https://github.com/planetarium/lib9c/pull/3001/commits/3274722638bd13d18c093c66200bfd61c7c2f91f)

2024-11-27 07:27 UTC, merged