Change skill selection logic.
planetarium/lib9c pull request #687
Opened 2021-10-26 11:37 UTC by hskim881028

### Description
- Separating Skills from CharacterBase
- Change skill select logic

### Version up actions 
- HackAndSlash 9 -> 10
- MimisbrunnrBattle 6 -> 7
- RankingBattle 7 -> 8

### Version up methods

- CharacterBase.UseSkill
- CharacterBase.Act
- CharacterBase.InitAI
- CharacterBase.ReduceSkillCooldown
- CharacterBase.ReduceSkillCooldown
- Skills.PostSelect
- Skills.Select
- Skills.ReduceCooldown
- EnemyPlayer.Spawn
- Player.Spawn
- Wave.Spawn
- StageSimulator.Simulate
- RankingSimulator.Simulate

### Add ObsoleteIndex  
- [V100084ObsoleteIndex ](https://github.com/planetarium/lib9c/pull/687/files#diff-849826ab0a4bef65fdd039428cb4eea1ce5908ca7a0b3d1a7c1152688ef5d671R65)
### Related Links

- [스킬 발동 확률 이상하다는 제보](https://app.asana.com/0/1133453747809944/1201231625530855/f)
- [notion](https://www.notion.so/planetarium/437457abb01141b3b1b1a4c6185eb5d3)

2021-11-02 06:42 UTC, hskim881028 commented
todo : add skills test until v100085

2021-11-02 06:42 UTC, boscohyun approved these changes

2021-11-02 07:46 UTC, boscohyun approved these changes

2021-11-02 08:15 UTC, boscohyun approved these changes

2021-11-02 09:15 UTC, longfin approved these changes

2021-11-08 02:48 UTC, boscohyun requested changes

2021-11-08 02:48 UTC, boscohyun commented on Lib9c/Policy/BlockPolicySource.cs
> +        public const long V100085ObsoleteIndex = 3_000_000;
```suggestion
        public const long V100086ObsoleteIndex = 3_000_000;
```

2021-11-09 01:56 UTC, boscohyun approved these changes

2021-11-09 02:04 UTC, merged