Feature/new arena scoring system
planetarium/lib9c pull request #749
Opened 2021-11-25 07:45 UTC by sonohoshi

### Description

In the past, defender in arena didn't get any score.
This is a new scoring system of defender.

### Related Links
[아레나 스코어 로직 수정 (진사람 점수 까기)](https://app.asana.com/0/958521740385861/1201406778349280/f)
[2021-11-22 9C 주간](https://www.notion.so/planetarium/2021-11-22-9C-7a0c525e580c4e87bbd2d904da6a26bf#acc7d16643c44d84950bfd58d30cdf29)

2021-11-30 05:21 UTC, hskim881028 requested changes

2021-11-30 05:21 UTC, hskim881028 commented on Lib9c/Action/RankingBattle8.cs
> +
```suggestion
CheckObsolete(BlockChain.Policy.BlockPolicySource.V100089ObsoleteIndex, context);
```
you need to add that code

2021-11-30 05:27 UTC, hskim881028 approved these changes

2021-11-30 05:27 UTC, hskim881028 commented on Lib9c/Battle/ArenaScoreHelper.cs
> +        public static int GetScore(int challengerRating, int defenderRating, BattleLog.Result result, out int defenderScore)
It seems nice to use a tuple to return both me and the enemy score.

2021-12-01 04:50 UTC, Namyujeong commented
![image](https://user-images.githubusercontent.com/41294407/144173916-976399b3-cdd5-4503-8db4-b6de3ca8053c.png)

2021-12-01 05:36 UTC, boscohyun commented
Fix in #764

2021-12-01 05:36 UTC, closed without merging