Fix minor
planetarium/lib9c pull request #783
Opened 2021-12-14 07:33 UTC by boscohyun

SSIA

2021-12-15 07:35 UTC, hskim881028 requested changes

2021-12-15 07:35 UTC, hskim881028 commented on Lib9c/Policy/BlockPolicySource.cs
> +        public const long V100092ObsoleteIndex = 3_001_000;
need to change from `V100092ObsoleteIndex` to `V100094ObsoleteIndex`

2021-12-16 05:56 UTC, hskim881028 approved these changes

2021-12-16 05:57 UTC, Unengine approved these changes

2021-12-16 06:22 UTC, merged