Change RankingSimulator Constructor Parameters
planetarium/lib9c pull request #866
Opened 2022-03-02 05:34 UTC by hskim881028

- In the `RankingSimulator` constructor, inject `Player` instead of `AvatarState`

- Version up list
   - ranking_battle10 -> ranking_battle11
   - RankingSimulator ->RankingSimulatorV1
   - New RankingSimulator
   
- Related Link
   - https://github.com/planetarium/NineChronicles/pull/1220
   -  [RankingBattle 등에서 AvatarState 를 풀로 쓰는 대신 전투에 필요한 중간 상태만 사용하게끔](https://app.asana.com/0/958521740385861/1201869821990665/f)

2022-03-03 01:39 UTC, ipdae requested changes
Since the  Player also contains all the information  from AvatarState, it seems like a change away from the original goal of reducing the weight of the model. I think it would be better to create a new model.

2022-03-04 02:46 UTC, boscohyun approved these changes

2022-03-04 02:47 UTC, boscohyun commented
CI was broken.😥

```
Error: Action/RankingBattle10.cs(78,25): error CS7036: There is no argument given that corresponds to the required formal parameter 'migrationRequired' of 'AccountStateDeltaExtensions.TryGetAvatarStateV2(IAccountStateDelta, Address, Address, out AvatarState, out bool)' [/home/runner/work/lib9c/lib9c/Lib9c/Lib9c.csproj]
```

2022-03-04 05:05 UTC, ipdae commented on Lib9c/Battle/SimulationEnemyPlayer.cs
> +    public readonly struct SimulationEnemyPlayer
i think we need add `MessagePackObject` for grpc serialize.

2022-03-07 04:43 UTC, boscohyun approved these changes

2022-03-07 04:58 UTC, sonohoshi approved these changes

2022-03-08 04:28 UTC, longfin commented
Do we need to bump RankingBattle action? I guess there is no changes about serialization format and execution result.

2022-03-10 02:26 UTC, closed without merging